source "https://rubygems.org"

# Just the Docs theme
gem "just-the-docs"

# GitHub Pages gem includes Jekyll and all dependencies
gem "github-pages", group: :jekyll_plugins

# Plugins
group :jekyll_plugins do
  gem "jekyll-seo-tag"
end

